### ISSUE TITLE
Published version

### ISSUE THREAD

**Issue by beriberikix** [mkovatsc/Copper4Cr#1]
Do you have plans to publish the extension and app to the Chrome Web Store?

**Comment by mkovatsc** [comment]
No, unfortunately Google shut that down... no new apps for Chrome.

See https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html?m=1

**Comment by beriberikix** [comment]
FYI @jwhui

I went down a bit of rat hole this morning and found an effort for CoAP over WebRTC ([draft](https://tools.ietf.org/html/draft-groves-coap-webrtcdc-00).) It is unclear to me whether this can be implemented over the existing RTCDataChannel in Chrome. @samdutton might know!

Also not sure if such an implementation would alleviate the need for a Chrome App all together.

**Comment by mkovatsc** [comment]
Using the standard Web API would work without the need for an app. However, there is no standard Web API for UDP, which you would need for RFC 7252 CoAP (opposed to CoAP-over-WebSockets or -WebRTC, which is mainly for stronger IoT devices and intermediaries, not for resource-constrained IoT devices).

Copper is mainly meant to show how nicely resource-constrained IoT devices can be integrated into the Web. (Firefox has a better API to register proper protocol handlers for URI schemes, which is much better than the Navigator.register... to redirect to a Web app at some http URI.)
