### ISSUE TITLE
Error on performing CoAP request in Chrome - Error while sending: net::ERR_NAME_NOT_RESOLVED (-105)

### ISSUE THREAD

**Issue by puliyathuranjith7** [mkovatsc/Copper4Cr#2]
Error on performing CoAP request in Chrome - Error while sending: net::ERR_NAME_NOT_RESOLVED (-105)

**Comment by ahmedmibrahim** [comment]
Did you fix it?

**Comment by mkovatsc** [comment]
Probably related to #4, should be fixed.
