### ISSUE TITLE
Plugin doesn't work with IPv6

### ISSUE THREAD

**Issue by AuSchell** [mkovatsc/Copper4Cr#4]
Hello,

I've noticed that the Copper Plugin for Chrome doesn't work with coap server which use IPv6. When i enter e.g. coap://[2000:620:190:ffff:300:4b00:66:1]:5683/ and i click on any command, i get the message "Error while sending: net::ERR_NAME_NOT_RESOLVED (-105)". The plugin for Mozilla Firefox on the other hand works fine. Is there a specific problem with chrome or are you working on that?

**Comment by dastarling** [comment]
I also have this issue, any response? Thanks

**Comment by SalvaHasan** [comment]
Same issue, it works fine with IPv4 but not with IPv4.

@mkovatsc

**Comment by mkovatsc** [comment]
[49fe9c6](https://github.com/mkovatsc/Copper4Cr/commit/49fe9c68ac22dd717e92659667ee9a7b0a71547f) should fix this.
